name: ELN GitHub Actions 1

on:
  workflow_dispatch:
  push:
    branches: [ ELN ]

jobs:
 TESTS:
    #runs-on: self-hosted # not working --> postgres service
    runs-on: ubuntu-latest
    #runs-on: ubuntu-18.04

    # keep
    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: 123456
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    # first checkout, before working dir is removed
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: ComPlat/chemotion_ELN
          path: .

      # - name: log ssh
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #   run: |
      #     #!/usr/bin/env bash
      #     set -euo pipefail
      #     eval $(ssh-agent -s);
      #     mkdir ~/.ssh/
      #     chmod 700 ~/.ssh
      #     echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-add ~/.ssh/id_rsa
      #     touch ~/.ssh/known_hosts
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts
      #     chmod 600 ~/.ssh/known_hosts
      #     ssh -o StrictHostKeyChecking=no docusaurus@eln.chemotion.net

      # TODO
      - name: change config files
        run: |
            #echo "PWD: $(pwd)"
            #echo "LS: $(ls)"
            cd config
            cp database.yml.gitlab database.yml
            cp -f storage.yml.example storage.yml
            touch datacollectors.yml
            cp -f profile_default.yml.example profile_default.yml
            touch klasses.json

      # - name: Docker copy
      #   run: |
      #       docker cp $(docker run -it -d complat/complat-ubuntu-runner:0.10.20):/home/gitlab-runner/node_modules .
      #       #docker cp $(docker run -it -d complat/complat-ubuntu-runner:0.10.20):/home/gitlab-runner .

      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: 12.22.1
      
      # TODO check diff work folders: https://github.community/t/copying-test-file-from-docker-container-to-github-repository/17977/2
      # docker --volume?
      # remove all preinstalled stuff?

      - name: Set up Ubuntu
        run: |
          echo "UBUNTU: $(cat /etc/os-release)"
          #sudo apt-get update
          #sudo apt-get install libboost-all-dev
          # cd /usr/lib/x86_64-linux-gnu/
          # ls


          # TODO rmv?
          # from install_production.sh
          sudo apt-get -y update
          sudo apt-get -y install ca-certificates apt-transport-https git curl dirmngr gnupg gnupg2 \
            autoconf automake bison libffi-dev libgdbm-dev libncurses5-dev openssh-server \
            g++ swig cmake libeigen3-dev \
            gconf-service libgconf-2-4 \
            libxslt-dev libxml2-dev \
            libyaml-dev sqlite3 libgmp-dev libreadline-dev libssl-dev \
            postgresql postgresql-client postgresql-contrib libpq-dev \
            imagemagick libmagic-dev libmagickcore-dev libmagickwand-dev \
            libsass-dev \
            libnspr4 libnss3 libpango1.0-0 libxss1  \
            tzdata python-dev libsqlite3-dev libboost-all-dev p7zip-full \
            ufw ranger htop \
            inkscape pandoc \
            xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable \
            fonts-crosextra-caladea fonts-crosextra-carlito \
            fonts-dejavu fonts-dejavu-core fonts-dejavu-extra fonts-liberation2 fonts-liberation \
            fonts-linuxlibertine fonts-noto-core fonts-noto-extra fonts-noto-ui-core \
            fonts-opensymbol fonts-sil-gentium fonts-sil-gentium-basic \
            --fix-missing


          # openbabel
          #sudo apt-get install -y libruby

          # pandoc
          curl -o /tmp/pandoc-2.10.1-1-amd64.deb -L https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-1-amd64.deb
          sudo dpkg -i /tmp/pandoc-2.10.1-1-amd64.deb

          # rvm
          #TODO
          #if gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          #else 
          gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          curl -sSL https://get.rvm.io | bash -s stable \
          && echo "source ~/.rvm/scripts/rvm" >> ~/.bashrc \
          && echo 'if [ -f ~/.bashrc ]; then \n  source ~/.bashrc\nfi' > ~/.bash_profile

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-v2-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-v2

      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@v1
        # with:
        #   ruby-version: 2.6.6
    
      - name: Bundle Install & unit test ruby
        env:
          PG_DATABASE: chemotion_test
          PG_HOST: localhost
          PG_USER: chemotion_test
          PG_PASSWORD: 123456
          RAILS_ENV: test
        run: |
          # download vendor
          wget --no-verbose https://bwsyncandshare.kit.edu/s/BXLL2HnwCx47qxC/download
          tar -xf download
          echo "LS: $(ls)"
          # TODO permissions vendor/bundle ?
          # bundle config path vendor/bundle
          source ~/.rvm/scripts/rvm && rvm install 2.6.6 && gem install bundler -v 1.17.3 --no-document &&  bundle install -j 3 --retry 3 --full-index --path vendor/bundle
          echo "HOME"
          cd ~/.rvm
          ls -la
          # gem install libruby
          # gem info libruby
          # echo "SIZE BUNDLE: $(du -bsh vendor/bundle)"
          # #echo "COUNT GEMS: $(find vendor/bundle -type f | wc -l)"
          # echo "CONFIGS"
          # echo "PWD: $(pwd)"
          # echo "BUNDLE: $(bundle -v)"
          # echo "RAILS: $(rails -v)"
          # echo "RUBY: $(ruby -v)"
          # cd vendor/bundle/ruby/2.6.0/bundler/gems/openbabel-gem-3e25548fd95c/openbabel/lib
          # # echo "LS openbabel lib"
          # # ls -la
          # # echo "LDD"
          # # ldd -v libruby.so.2.6
          # ldd -v openbabel.so
          # source ~/.rvm/scripts/rvm && RAILS_ENV=test bundle exec rake db:test:prepare --trace
          

      # - name: unit test ruby
      #   env:
      #     PG_DATABASE: chemotion_test
      #     PG_HOST: localhost
      #     PG_USER: chemotion_test
      #     PG_PASSWORD: 123456
      #     RAILS_ENV: test
      #     # WITH_COVERAGE: true
      #     # DISABLE_SPRING: 1
      #   run: |
      #     source ~/.rvm/scripts/rvm && RAILS_ENV=test bundle exec rake db:test:prepare --trace
      #     ldd -v libopenbabel.so.5
          # bundle exec rspec spec/api/user_api_spec.rb --trace
          # bundle exec rspec --exclude-pattern spec/{features}/**/*_spec.rb

      #  NODE
      # - name: Cache node modules
      #   uses: actions/cache@v2
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      # - name: Set up node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 12.22.1
      
      # - name: Install node modules
      #   # if: steps.cache.outputs.cache-hit != 'true'
      #   run: |
      #     echo "PWD: $(pwd)"
      #     #echo "LS: $(ls)"

      #     # curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      #     # export NVM_DIR="$HOME/.nvm"
      #     # [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      #     # [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

      #     # unistall preinstalled
      #     # nvm use system
      #     # npm uninstall -g a_module

      #     #nvm install v12.22.1
      #     npm install -g npm@7.11.1

      #     echo "NPM: $(npm -v)"
      #     #echo "NVM: $(nvm -v)"

      #     # download preinstalled node_mdoules
      #     wget --no-verbose https://bwsyncandshare.kit.edu/s/S5pmzsC2SNZEEZ7/download
      #     tar -xf download
      #     echo "SIZE NODE MODULES 0: $(du -bsh node_modules)"
      #     echo "COUNT NODE MODULES 0: $(find node_modules -type f | wc -l)"

      #     npm i
      #     echo "SIZE NODE MODULES 1: $(du -bsh node_modules)"
      #     echo "COUNT NODE MODULES 1: $(find node_modules -type f | wc -l)"
      #     npm test

      #     # source ~/.nvm/nvm.sh && nvm use && npm i
      #     # source ~/.nvm/nvm.sh && nvm use && npm test
          
      
      # - name: test postgres
      #   env:
      #     PG_DATABASE: chemotion_test
      #     PG_HOST: localhost
      #     PG_USER: chemotion_test
      #     PG_PASSWORD: 123456
      #     RAILS_ENV: test
      #     # WITH_COVERAGE: true
      #     # DISABLE_SPRING: 1
      #   run: |
      #       sudo -u postgres psql
      
      # - name: check
      #   run: |            
      #       cd docker
      #       echo "PWD: $(pwd)"
      #       echo "LS: $(ls)"

      # - name: Check file existence
      #   id: check_files
      #   uses: andstor/file-existence-action@v1
      #   with:
      #     files: 
      # - name: checkout
      #   uses: actions/checkout@v2
      #   with:
      #     repository: ComPlat/chemotion_ELN
      #     path: gitlab-runner

      # - name: Download build artifacts
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: gitlab-runner
      #     path: gitlab-runner
