name: self-hosted runner 2

on:
  workflow_dispatch:
  push:
    branches: [ ELN ]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "gitlab-runner/shared"
      - name: docker pull
        # todo check for newer tag
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          docker pull complat/complat-ubuntu-runner:0.10.20
          docker cp $(docker run -it -d complat/complat-ubuntu-runner:0.10.20):/home/gitlab-runner .
          # todo check if fully pulled

  # checkout:
  #   needs: docker
  #   runs-on: self-hosted
  #   steps:
  #     - name: Check file existence
  #       id: check_files
  #       uses: andstor/file-existence-action@v1
  #       with:
  #         files: "gitlab-runner/app"
  #     - name: init checkout ELN
  #     # todo always checkout?
  #       if: steps.check_files.outputs.files_exists == 'false' 
  #       uses: actions/checkout@v2
  #       with:
  #         repository: ComPlat/chemotion_ELN
  #         path: gitlab-runner

  config_files:
    needs: docker
    #needs: checkout
    runs-on: self-hosted
    steps:
      - name: change config files
        run: |
            pwd
            ls
            cd gitlab-runner/config
            cp database.yml.example database.yml
            cp -f storage.yml.example storage.yml
            touch datacollectors.yml
            cp -f profile_default.yml.example profile_default.yml
            touch klasses.json
  
  # packages:
  #   needs: config_files
  #   # needs: docker
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/cache@v2
  #       with:
  #         path: gitlab-runner/shared
  #         key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-gems-
  #     - run: |
  #           cd gitlab-runner
  #           # && gem install bundler -v 1.17.3 --no-document 
  #           #source ~/.rvm/scripts/rvm && 
  #           bundle install -j 3 --path shared/bundle
  #           source ~/.nvm/nvm.sh && nvm use && npm i
  #           echo "NPM"
  #           npm list | grep react@
  #           echo "GEMS"
  #           gem list
  #           echo "OPENBAEL"
  #           gem which openbabel
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     sudo: false

  # testjs:
  #   needs: packages
  #   #needs: docker
  #   runs-on: self-hosted
  #   steps:
  #       - run: |
  #           cd gitlab-runner
  #           #echo "NPM"
  #           source ~/.nvm/nvm.sh && nvm use && RAILS_ENV=test bundle exec rake db:test:prepare --trace && npm test
  #           #source ~/.rvm/scripts/rvm && 
  #                       #npm test
  #           #source ~/.nvm/nvm.sh && nvm use && npm test
  #         env:
  #           POSTGRES_HOST: localhost
  #           POSTGRES_PORT: 5432
  #       - name: Setup tmate session
  #         uses: mxschmitt/action-tmate@v3
  #         with:
  #           sudo: false
  
  test:
    needs: config_files
    runs-on: self-hosted
    steps:
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          #path: gitlab-runner/shared/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: install packages
        run: |
            cd gitlab-runner
            rm Gemfile.lock
            # npm install -g npm@7.11.1
            source ~/.nvm/nvm.sh && nvm use && npm i
            echo "BUNDLE"
            bundle install -j 3 --path vendor/bundle  --retry 3
            #gem install --install-dir shared/bundle openbabel
            #  
            # bundle config list
            echo "GEMS"
            gem env
            # echo "OPENBAEL"
            # gem which openbabel
      - name: testrb
        run: |
          cd gitlab-runner
          rspec --exclude-pattern spec/{features}/**/*_spec.rb
      - name: testjs
        run: |
          cd gitlab-runner
          source ~/.nvm/nvm.sh && nvm use && npm test 
    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

  # testacceptance:
  #   needs: packages
  #   runs-on: self-hosted
  #   steps:
  #       - run: |
  #           cd gitlab-runner
  #           rspec spec/features
  #   env:
  #     POSTGRES_HOST: localhost
  #     POSTGRES_PORT: 5432



